# Generated by Django 2.1.7 on 2019-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=12)),
                ('c_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('c_name', models.CharField(max_length=200)),
            ],
        ),
    ]
