# Generated by Django 2.1.7 on 2019-03-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_center',
            fields=[
                ('sc_id', models.AutoField(primary_key=True, serialize=False)),
                ('sc_name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=12)),
                ('area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=12)),
                ('zipcode', models.CharField(max_length=6)),
                ('image', models.ImageField(blank=True, upload_to='sc_image')),
                ('sc_address', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='combo',
            name='id',
        ),
        migrations.AlterField(
            model_name='combo',
            name='c_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
