# Generated by Django 2.1.7 on 2019-03-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0002_auto_20190329_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('c_id', models.IntegerField(max_length=2)),
                ('c_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
