# Generated by Django 2.1.7 on 2019-03-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_id',
            field=models.CharField(max_length=2),
        ),
    ]
