# Generated by Django 2.1.7 on 2019-03-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0004_auto_20190329_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='model',
            fields=[
                ('m_id', models.CharField(max_length=2)),
                ('m_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Groomautoapp.company')),
            ],
        ),
    ]
