# Generated by Django 2.1.7 on 2019-03-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0005_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=150)),
            ],
        ),
    ]
