# Generated by Django 2.1.7 on 2019-03-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile_no', models.CharField(max_length=12)),
                ('msg', models.CharField(max_length=60)),
            ],
        ),
    ]
