# Generated by Django 2.1.7 on 2019-03-30 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0008_auto_20190329_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('gmail', models.EmailField(max_length=30)),
                ('age', models.CharField(max_length=2)),
                ('m_no', models.CharField(max_length=12)),
                ('area', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=12)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sc_name', models.CharField(max_length=100)),
                ('sc_address', models.CharField(max_length=100)),
                ('c_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('v_number', models.CharField(max_length=20)),
                ('m_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Groomautoapp.model')),
            ],
        ),
    ]
