# Generated by Django 2.1.7 on 2019-04-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Groomautoapp.service_center'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='sc_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
