# Generated by Django 2.1.7 on 2019-04-01 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0010_auto_20190401_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Groomautoapp.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sc_address',
            field=models.CharField(max_length=150),
        ),
    ]
