# Generated by Django 2.0 on 2019-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0013_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repair_date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
