# Generated by Django 2.0 on 2019-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0014_auto_20190413_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repair_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
