# Generated by Django 2.1.7 on 2019-04-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0016_auto_20190423_0553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='combo',
            new_name='package',
        ),
    ]
