# Generated by Django 2.1.7 on 2019-04-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0020_remove_repair_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='u_login',
            new_name='u_detail',
        ),
    ]
