# Generated by Django 2.1.7 on 2019-04-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0022_auto_20190425_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_center',
            name='sc_id',
        ),
        migrations.AlterField(
            model_name='service_center',
            name='sc_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
