# Generated by Django 2.1.7 on 2019-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0023_auto_20190425_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ow_detail',
            fields=[
                ('ow_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=12)),
                ('sc_address', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=12)),
            ],
        ),
    ]
