# Generated by Django 2.1.7 on 2019-04-25 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0024_ow_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 5, 34, 0, 617392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='vehicle_company',
            field=models.CharField(choices=[('Hero', 'Hero'), ('Honda', 'Honda'), ('Bajaj', 'Bajaj'), ('Tvs', 'Tvs'), ('Yamaha', 'yamaha'), ('suzuki', 'suzuki'), ('KTM', 'KTm')], max_length=64),
        ),
    ]
