# Generated by Django 2.1.7 on 2019-04-25 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0025_auto_20190425_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='gal',
            fields=[
                ('galname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gal_pic', models.ImageField(upload_to='gallery_pic')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 6, 7, 56, 83520, tzinfo=utc)),
        ),
    ]
