# Generated by Django 2.1.7 on 2019-04-25 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0026_auto_20190425_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 6, 8, 5, 652110, tzinfo=utc)),
        ),
    ]
