# Generated by Django 2.1.7 on 2019-04-25 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0027_auto_20190425_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gal',
            new_name='gallery',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gal_pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='galname',
            new_name='imgname',
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 6, 23, 5, 230418, tzinfo=utc)),
        ),
    ]
