# Generated by Django 2.1.7 on 2019-04-25 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0028_auto_20190425_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='ow_detail',
            name='pincode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 6, 39, 2, 107099, tzinfo=utc)),
        ),
    ]
