# Generated by Django 2.1.7 on 2019-04-25 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0029_auto_20190425_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 6, 47, 50, 561671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='package',
            name='co_name',
            field=models.CharField(max_length=500),
        ),
    ]
