# Generated by Django 3.0.1 on 2020-02-17 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Groomautoapp', '0030_auto_20190425_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_time',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 17, 17, 35, 5, 813213, tzinfo=utc)),
        ),
    ]
